version: '3.8'

services:
  db:
    image: postgres:14.1-alpine
    volumes:
      - ./db/init:/docker-entrypoint-initdb.d
      - ./db/data:/var/lib/postgresql/data
    restart: always
    environment:
      POSTGRES_PASSWORD_FILE: /run/secrets/POSTGRES_PASSWORD
      POSTGRES_USER_FILE: /run/secrets/POSTGRES_USER
      POSTGRES_DB: warehouse
    ports:
      - 5432:5432
    networks:
      - common
    secrets:
      - POSTGRES_PASSWORD
      - POSTGRES_USER
  etl:
    build:
      context: ./etl
    volumes:
      - ./etl:/etl
      - ~/.local/share/evolution:/evolution/.local/share/evolution
      - ~/.config/evolution:/evolution/.config/evolution
    depends_on:
      - db
    networks:
      - common
    secrets:
      - POSTGRES_PASSWORD
      - POSTGRES_USER
      - FITBIT_USER_ID
      - FITBIT_ACCESS_TOKEN
  metabase:
    image: metabase/metabase:latest
    volumes:
      - /dev/urandom:/dev/random:ro
    ports:
      - 3000:3000
    environment: 
      MB_DB_TYPE: postgres
      MB_DB_DBNAME: metabase
      MB_DB_PORT: 5432
      MB_DB_HOST: db
    env_file: secrets/metabase.env
    networks: 
      - common
    depends_on:
      - db
    secrets:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
networks:
  common:
    driver: bridge

secrets:
  POSTGRES_USER:
    file: secrets/POSTGRES_USER.secret
  POSTGRES_PASSWORD:
    file: secrets/POSTGRES_PASSWORD.secret
  FITBIT_USER_ID:
    file: secrets/FITBIT_USER_ID.secret
  FITBIT_ACCESS_TOKEN:
    file: secrets/FITBIT_ACCESS_TOKEN.secret
