version: '3.8'

services:
  db:
    image: postgres:14.1-alpine
    volumes:
      - ./db/init:/docker-entrypoint-initdb.d
      - ./db/data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: warehouse
    ports:
      - 5432:5432
    env_file: secrets/postgres.env
    restart: "no"
  etl:
    build:
      context: ./etl
    volumes:
      - ./etl:/etl
      - ./etl/airflow/dags:/airflow/home/dags
      - ./etl/airflow/airflow.cfg:/airflow/home/airflow.cfg
      - ~/.local/share/evolution:/evolution/.local/share/evolution
      - ~/.config/evolution:/evolution/.config/evolution
    ports:
      - 8080:8080
    depends_on:
      - db
    env_file:
      - secrets/fitbit.env
      - secrets/postgres.env
      - secrets/airflow.env
  metabase:
    image: metabase/metabase:latest
    volumes:
      - /dev/urandom:/dev/random:ro
    ports:
      - 3000:3000
    environment: 
      MB_DB_TYPE: postgres
      MB_DB_DBNAME: metabase
      MB_DB_PORT: 5432
      MB_DB_HOST: db
    env_file: secrets/metabase.env
    depends_on:
      - db
    restart: "no"
